import { UsersData as UsersDataType } from "@/types/admin/users";

export const UsersData: UsersDataType[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    role: "Admin",
    created_at: "2025-01-05T10:30:00Z",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    role: "User",
    created_at: "2025-02-12T14:45:00Z",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.j@example.com",
    role: "Admin",
    created_at: "2025-03-18T09:15:00Z",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.w@example.com",
    role: "User",
    created_at: "2025-04-22T11:20:00Z",
  },
  {
    id: "5",
    firstName: "David",
    lastName: "Brown",
    email: "david.b@example.com",
    role: "User",
    created_at: "2025-05-09T13:10:00Z",
  },
  {
    id: "6",
    firstName: "Sarah",
    lastName: "Miller",
    email: "sarah.m@example.com",
    role: "Admin",
    created_at: "2025-06-14T16:30:00Z",
  },
  {
    id: "7",
    firstName: "Robert",
    lastName: "Wilson",
    email: "robert.w@example.com",
    role: "User",
    created_at: "2025-07-21T08:45:00Z",
  },
  {
    id: "8",
    firstName: "Jennifer",
    lastName: "Taylor",
    email: "jennifer.t@example.com",
    role: "User",
    created_at: "2025-08-16T10:15:00Z",
  },
  {
    id: "9",
    firstName: "Thomas",
    lastName: "Anderson",
    email: "thomas.a@example.com",
    role: "Admin",
    created_at: "2025-09-30T14:20:00Z",
  },
  {
    id: "10",
    firstName: "Lisa",
    lastName: "Thomas",
    email: "lisa.t@example.com",
    role: "User",
    created_at: "2025-10-11T12:30:00Z",
  },
];
