import { AuditLogsData as AuditLogsDataType } from "@/types/admin/audit-logs";

export const AuditLogsData: AuditLogsDataType[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    action: "login",
    status: "success",
    created_at: "2025-01-03T10:30:00Z",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    action: "logout",
    status: "success",
    created_at: "2025-02-07T11:00:00Z",
  },
  {
    id: "3",
    firstName: "Mark",
    lastName: "Johnson",
    action: "update profile",
    status: "success",
    created_at: "2025-03-12T09:45:00Z",
  },
  {
    id: "4",
    firstName: "Alice",
    lastName: "Brown",
    action: "change password",
    status: "failed",
    created_at: "2025-04-01T10:10:00Z",
  },
  {
    id: "5",
    firstName: "Robert",
    lastName: "Wilson",
    action: "delete account",
    status: "success",
    created_at: "2025-05-15T08:30:00Z",
  },
  {
    id: "6",
    firstName: "Emily",
    lastName: "Davis",
    action: "login",
    status: "failed",
    created_at: "2025-06-20T08:45:00Z",
  },
  {
    id: "7",
    firstName: "Michael",
    lastName: "Clark",
    action: "export data",
    status: "success",
    created_at: "2025-07-10T12:20:00Z",
  },
  {
    id: "8",
    firstName: "Sarah",
    lastName: "Lee",
    action: "reset password",
    status: "success",
    created_at: "2025-08-03T14:00:00Z",
  },
  {
    id: "9",
    firstName: "David",
    lastName: "Martinez",
    action: "login",
    status: "success",
    created_at: "2025-09-25T07:15:00Z",
  },
  {
    id: "10",
    firstName: "Laura",
    lastName: "Anderson",
    action: "update email",
    status: "success",
    created_at: "2025-10-18T09:40:00Z",
  },
];
